import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Витрина товаров upstream',
    short_name: 'Витрина',
    description: 'Каталог товаров с ценами и кэшбэком',
    start_url: '/',
    display: 'standalone',
    background_color: '#f8fafc',
    theme_color: '#2f6fed',
    lang: 'ru-RU',
    // Icons are generated by `app/icon.tsx` / `app/apple-icon.tsx` at build
    // time, so they are not listed as files here — Next serves them from the
    // routes those files define.
  };
}